version: '3'

services:
  server:
    image: golang:1.15.2
    restart: always
    ports:
      - 8080:8080
    volumes:
      - .:/app
      - $GOPATH/pkg/mod:/go/pkg/mod
    working_dir: /app
    environment:
      MYSQL_HOST: mysql:3306
      MYSQL_USER: ming
      MYSQL_PASSWORD: ming
      MYSQL_DATABASE: test
      REDIS_HOST: redis:6379
      HTTP_PORT: 8080
    command: go run .
  mysql:
    image: mysql:8.0
    restart: always
    ports:
      - 3306:3306
    command: --default-authentication-plugin=mysql_native_password
             --character-set-server=utf8mb4
             --collation-server=utf8mb4_general_ci
             --lower_case_table_names=1
             --max_allowed_packet=128M;
    environment:
      MYSQL_USER: ming
      MYSQL_PASSWORD: ming
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test
    volumes:
      - mysql_data:/var/lib/mysql
  redis:
    image: redis:5.0.1-alpine
    ports:
      - 6379:6379
  
volumes:
  mysql_data: